CREATE DATABASE IF NOT EXISTS TACOSPIPEV1;
USE TACOSPIPEV1;

CREATE TABLE IF NOT EXISTS USUARIOS(

ID int NOT NULL AUTO_INCREMENT,
CORREO VARCHAR(255) NOT NULL UNIQUE ,
CONTRASENA VARCHAR(40) NOT NULL,
NOMBRE VARCHAR(100),
TELEFONO VARCHAR(12),
DIRECCION varchar(100),
ACTIVO BOOLEAN default TRUE,


PRIMARY KEY (ID)


);



SELECT * FROM USUARIOS;